name = "AssociativeScenesSimulation"
uuid = "c1d5329f-99ae-41bc-a3b7-c4746bb0a699"
authors = ["Daniel Bulanda <daniel@bulanda.net>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
